name: Recess All Day
favicon: null
layout_spectrum: 0.13183
typography_spectrum: 0.16596
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#28e5f6'
    - '#4c3217'
    - '#439426'
    - '#fee866'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
